# Generated by Django 5.0.6 on 2024-07-05 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0006_remove_membro_id_alter_membro_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='libreria.membro'),
        ),
    ]
