# Generated by Django 5.1.6 on 2025-02-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0008_alter_libro_image_alter_libro_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='shelf',
            field=models.CharField(default='000', max_length=3),
        ),
        migrations.AlterField(
            model_name='libro',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='libro',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
