# Generated by Django 5.1.6 on 2025-02-27 19:16

import libreria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0009_libro_shelf_alter_libro_author_alter_libro_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='libro',
            name='image',
            field=models.ImageField(blank=True, default='./static/libreria/libro.png', null=True, upload_to='media/', validators=[libreria.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='libro',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
