# Generated by Django 5.1.6 on 2025-03-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0010_alter_libro_author_alter_libro_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='category',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='libro',
            name='shelf',
            field=models.CharField(default='999', max_length=3),
        ),
    ]
